version: '3.8'

services:

  mongo:
    container_name: docker_mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"  # "port_host:port_container"

    volumes: 
      - $PWD/data:/data/db